baseURL = "https://www.crisisfighters.org/"
title = "CrisisFighters.org"
theme = "ananke"

MetaDataFormat = "yaml"
SectionPagesMenu = "main"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe= true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  custom_css = ["style.css"]

[blackfriday]
  plainIDAnchors = true
  # Thanks to https://code.luasoftware.com/tutorials/hugo/how-to-create-link-with-target-blanks-in-hugo-markdown/
  hrefTargetBlank = true

DefaultContentLanguage = "en"
languageCode = "en-us"

[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
  [languages.de]
    weight = 2
    [languages.de.params]
      languageCode = "de-de"
