
defaultContentLanguage = "en-us"

baseURL = "https://www.crisisfighters.org/"
title = "CrisisFighters.org"
theme = "cftheme"

MetaDataFormat = "yaml"
SectionPagesMenu = "main"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  custom_css = ["style.css"]

[blackfriday]
  plainIDAnchors = true
  # Thanks to https://code.luasoftware.com/tutorials/hugo/how-to-create-link-with-target-blanks-in-hugo-markdown/
  hrefTargetBlank = true

defaultContentLanguage = "en-us"
languageCode = "en-us"

[languages]
  [languages.en-us]
    weight = 1
    [languages.en-us.params]
  [languages.de-de]
    weight = 2
    [languages.de-de.params]
      languageCode = "de-de"
