name = "CrisisFighters Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/crisisfighters/crisisfighters.org/blob/master/LICENSE"
description = "A purpose-specific theme for CrisisFighters.org. Based on Hugo's Ananke theme!"
homepage = "https://github.com/crisisfighters/crisisfighters.org"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts",]
min_version = "0.30.2"

[author]
  name = "Alexander Thiel"
  homepage = "https://github.com/reasn"
